services:
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - IPFS_RPC_URL=${IPFS_RPC_URL}
      - IPFS_RPC_USER=${IPFS_RPC_USER}
      - IPFS_RPC_PASSWORD=${IPFS_RPC_PASSWORD}
      - NETWORK_ID=${NETWORK_ID}
