name: Frontend

on:
  pull_request:
  push:
    branches: [main]

jobs:
  elm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cache elm stuff
        uses: actions/cache@v4
        with:
          path: |
            ~/.elm
            frontend/elm-stuff
          key: elm-${{ hashFiles('frontend/elm.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run make

      - name: Check code formatting
        run: npm run format:validate

      - name: List check
        run: npm run lint
