name: Frontend

on:
  pull_request:
  push:
    branches: [production]

jobs:
  elm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 1
          shallow-submodules: true # Also make submodules shallow clones

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cache elm stuff
        uses: actions/cache@v4
        with:
          path: |
            ~/.elm
            frontend/elm-stuff
          key: elm-${{ hashFiles('frontend/elm.json') }}

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build project
        working-directory: frontend
        run: npm run make

      - name: Check code formatting
        working-directory: frontend
        run: npm run format:validate

      - name: List check
        working-directory: frontend
        run: npm run lint
